import type { InventoryItem, VehicleProfile } from '@/types/inventory';

export const MOCK_VEHICLE: VehicleProfile = {
    registration: 'CA 456-789',
    type:         '1-ton Bakkie',
    maxWeightKg:  300,
};

export const MOCK_INVENTORY: InventoryItem[] = [
    // ── Delivered ────────────────────────────────────────────────────────────
    {
        id:              'inv-001',
        poNumber:        'PO-4418',
        sku:             'TLR-100150',
        productName:     'Thermal Label Roll 100×150mm',
        qtyLoaded:       20,
        qtyDelivered:    20,
        unitWeightKg:    0.44,
        recipient:       'Rapid Print Solutions',
        deliveryAddress: '12 Loop Street, Cape Town CBD, 8001',
        status:          'DELIVERED',
        deliveredAt:     new Date(new Date().setHours(8, 47, 0, 0)).toISOString(),
    },
    {
        id:              'inv-002',
        poNumber:        'PO-4418',
        sku:             'KPM-250350',
        productName:     'Kraft Paper Mailer 250×350mm',
        qtyLoaded:       200,
        qtyDelivered:    200,
        unitWeightKg:    0.05,
        recipient:       'Rapid Print Solutions',
        deliveryAddress: '12 Loop Street, Cape Town CBD, 8001',
        status:          'DELIVERED',
        deliveredAt:     new Date(new Date().setHours(8, 47, 0, 0)).toISOString(),
    },
    // ── Loaded / in transit ───────────────────────────────────────────────────
    {
        id:              'inv-003',
        poNumber:        'PO-4421',
        sku:             'BWR-1000-50',
        productName:     'Bubble Wrap Roll 1000×50m',
        qtyLoaded:       2,
        qtyDelivered:    0,
        unitWeightKg:    6.25,
        recipient:       'Cape Carton Co.',
        deliveryAddress: '34 Buitenkant Street, Gardens, Cape Town, 8001',
        status:          'LOADED',
    },
    {
        id:              'inv-004',
        poNumber:        'PO-4421',
        sku:             'CEP-50',
        productName:     'Cardboard Edge Protectors 50mm',
        qtyLoaded:       60,
        qtyDelivered:    0,
        unitWeightKg:    0.12,
        recipient:       'Cape Carton Co.',
        deliveryAddress: '34 Buitenkant Street, Gardens, Cape Town, 8001',
        status:          'LOADED',
    },
    {
        id:              'inv-005',
        poNumber:        'PO-4422',
        sku:             'CBA4-SW',
        productName:     'Corrugated Box A4 Single-Wall',
        qtyLoaded:       150,
        qtyDelivered:    0,
        unitWeightKg:    0.28,
        recipient:       'Greenleaf Packaging',
        deliveryAddress: '7 Adderley Street, Cape Town CBD, 8001',
        status:          'LOADED',
    },
    {
        id:              'inv-006',
        poNumber:        'PO-4422',
        sku:             'CBA3-DW',
        productName:     'Corrugated Box A3 Double-Wall',
        qtyLoaded:       80,
        qtyDelivered:    0,
        unitWeightKg:    0.42,
        recipient:       'Greenleaf Packaging',
        deliveryAddress: '7 Adderley Street, Cape Town CBD, 8001',
        status:          'LOADED',
    },
    {
        id:              'inv-007',
        poNumber:        'PO-4423',
        sku:             'SWF-500300',
        productName:     'Stretch Wrap Film 500mm×300m',
        qtyLoaded:       4,
        qtyDelivered:    0,
        unitWeightKg:    3.50,
        recipient:       'Metro Logistics Hub',
        deliveryAddress: '1 Voortrekker Road, Bellville, 7530',
        status:          'LOADED',
    },
    {
        id:              'inv-008',
        poNumber:        'PO-4423',
        sku:             'PWD-HANDLE',
        productName:     'Pallet Wrap Dispenser Handle',
        qtyLoaded:       2,
        qtyDelivered:    0,
        unitWeightKg:    0.45,
        recipient:       'Metro Logistics Hub',
        deliveryAddress: '1 Voortrekker Road, Bellville, 7530',
        status:          'LOADED',
    },
    // ── Failed delivery ───────────────────────────────────────────────────────
    {
        id:              'inv-009',
        poNumber:        'PO-4419',
        sku:             'PSB-12MM',
        productName:     'Polypropylene Strapping Band 12mm',
        qtyLoaded:       12,
        qtyDelivered:    0,
        unitWeightKg:    2.60,
        recipient:       'Atlantic Freight',
        deliveryAddress: '99 Marine Drive, Table View, 7441',
        status:          'FAILED',
        failureNote:     'Recipient warehouse closed — rescheduled.',
    },
];
