import type { InventoryItem, VehicleProfile } from '@/types/inventory';

export const MOCK_VEHICLE: VehicleProfile = {
    registration: 'CA 456-789',
    type:         '1-ton Bakkie',
    maxWeightKg:  300,
};

export const MOCK_INVENTORY: InventoryItem[] = [
    {
        id:              'inv-001',
        poNumber:        'PO-4418',
        sku:             'TLR-100150',
        productName:     'Thermal Label Roll 100×150mm',
        productImage:    'https://images.unsplash.com/photo-1605833559748-03820257326a?q=80&w=200&h=200&auto=format&fit=crop',
        vendorName:      'LabelTech',
        qtyOrdered:      20,
        qtyLoaded:       20,
        qtyDelivered:    20,
        unitWeightKg:    0.44,
        recipient:       'Rapid Print Solutions',
        destinations:    ['Rapid Print Solutions'],
        deliveryAddress: '12 Loop Street, Cape Town CBD, 8001',
        status:          'DELIVERED',
        invStatus:       'COMPLETE',
        condition:       'GOOD',
        deliveredAt:     new Date(new Date().setHours(8, 47, 0, 0)).toISOString(),
    },
    {
        id:              'inv-002',
        poNumber:        'PO-4418',
        sku:             'KPM-250350',
        productName:     'Kraft Paper Mailer 250×350mm',
        productImage:    'https://images.unsplash.com/photo-1589939705384-5185138a047a?q=80&w=200&h=200&auto=format&fit=crop',
        vendorName:      'PackMaster SA',
        qtyOrdered:      200,
        qtyLoaded:       200,
        qtyDelivered:    200,
        unitWeightKg:    0.05,
        recipient:       'Rapid Print Solutions',
        destinations:    ['Rapid Print Solutions'],
        deliveryAddress: '12 Loop Street, Cape Town CBD, 8001',
        status:          'DELIVERED',
        invStatus:       'COMPLETE',
        condition:       'GOOD',
        deliveredAt:     new Date(new Date().setHours(8, 47, 0, 0)).toISOString(),
    },
    {
        id:              'inv-003',
        poNumber:        'PO-4421',
        sku:             'BWR-1000-50',
        productName:     'Bubble Wrap Roll 1000×50m',
        productImage:    'https://images.unsplash.com/photo-1595246140625-573b715d11dc?q=80&w=200&h=200&auto=format&fit=crop',
        vendorName:      'PackMaster SA',
        qtyOrdered:      2,
        qtyLoaded:       2,
        qtyDelivered:    0,
        unitWeightKg:    6.25,
        recipient:       'Cape Carton Co.',
        destinations:    ['Cape Carton Co.', 'Metro Logistics Hub'],
        deliveryAddress: '34 Buitenkant Street, Gardens, Cape Town, 8001',
        status:          'LOADED',
        invStatus:       'PENDING',
        condition:       'GOOD',
    },
    {
        id:              'inv-004',
        poNumber:        'PO-4421',
        sku:             'CEP-50',
        productName:     'Cardboard Edge Protectors 50mm',
        productImage:    'https://images.unsplash.com/photo-1530587191325-3db32d826c18?q=80&w=200&h=200&auto=format&fit=crop',
        vendorName:      'BoxCo Industries',
        qtyOrdered:      60,
        qtyLoaded:       60,
        qtyDelivered:    15,
        unitWeightKg:    0.12,
        recipient:       'Cape Carton Co.',
        destinations:    ['Cape Carton Co.', 'Greenleaf Packaging'],
        deliveryAddress: '34 Buitenkant Street, Gardens, Cape Town, 8001',
        status:          'LOADED',
        invStatus:       'PARTIAL',
        condition:       'PARTIALLY_DAMAGED',
        damagedCount:    2,
    },
    {
        id:              'inv-005',
        poNumber:        'PO-4422',
        sku:             'CBA4-SW',
        productName:     'Corrugated Box A4 Single-Wall',
        productImage:    'https://images.unsplash.com/photo-1529390079861-591de354faf5?q=80&w=200&h=200&auto=format&fit=crop',
        vendorName:      'BoxCo Industries',
        qtyOrdered:      150,
        qtyLoaded:       146,
        qtyDelivered:    0,
        unitWeightKg:    0.28,
        recipient:       'Greenleaf Packaging',
        destinations:    ['Greenleaf Packaging'],
        deliveryAddress: '7 Adderley Street, Cape Town CBD, 8001',
        status:          'LOADED',
        invStatus:       'PENDING',
        condition:       'GOOD',
    },
    {
        id:              'inv-006',
        poNumber:        'PO-4422',
        sku:             'CBA3-DW',
        productName:     'Corrugated Box A3 Double-Wall',
        productImage:    'https://images.unsplash.com/photo-1512418490979-92798ced1380?q=80&w=200&h=200&auto=format&fit=crop',
        vendorName:      'BoxCo Industries',
        qtyOrdered:      80,
        qtyLoaded:       80,
        qtyDelivered:    0,
        unitWeightKg:    0.42,
        recipient:       'Greenleaf Packaging',
        destinations:    ['Greenleaf Packaging'],
        deliveryAddress: '7 Adderley Street, Cape Town CBD, 8001',
        status:          'LOADED',
        invStatus:       'PENDING',
        condition:       'GOOD',
    },
    {
        id:              'inv-007',
        poNumber:        'PO-4423',
        sku:             'SWF-500300',
        productName:     'Stretch Wrap Film 500mm×300m',
        productImage:    'https://images.unsplash.com/photo-1620912189865-1e8a33da4c59?q=80&w=200&h=200&auto=format&fit=crop',
        vendorName:      'WrapRight',
        qtyOrdered:      4,
        qtyLoaded:       4,
        qtyDelivered:    0,
        unitWeightKg:    3.50,
        recipient:       'Metro Logistics Hub',
        destinations:    ['Metro Logistics Hub'],
        deliveryAddress: '1 Voortrekker Road, Bellville, 7530',
        status:          'LOADED',
        invStatus:       'PENDING',
        condition:       'DAMAGED',
    },
    {
        id:              'inv-008',
        poNumber:        'PO-4423',
        sku:             'PWD-HANDLE',
        productName:     'Pallet Wrap Dispenser Handle',
        productImage:    'https://images.unsplash.com/photo-1589939705384-5185138a047a?q=80&w=200&h=200&auto=format&fit=crop',
        vendorName:      'WrapRight',
        qtyOrdered:      2,
        qtyLoaded:       2,
        qtyDelivered:    0,
        unitWeightKg:    0.45,
        recipient:       'Metro Logistics Hub',
        destinations:    ['Metro Logistics Hub'],
        deliveryAddress: '1 Voortrekker Road, Bellville, 7530',
        status:          'LOADED',
        invStatus:       'PENDING',
        condition:       'GOOD',
    },
    {
        id:              'inv-009',
        poNumber:        'PO-4419',
        sku:             'PSB-12MM',
        productName:     'Polypropylene Strapping Band 12mm',
        productImage:    'https://images.unsplash.com/photo-1586769852836-bc069f19e1b6?q=80&w=200&h=200&auto=format&fit=crop',
        vendorName:      'StrapSafe',
        qtyOrdered:      12,
        qtyLoaded:       12,
        qtyDelivered:    0,
        unitWeightKg:    2.60,
        recipient:       'Atlantic Freight',
        destinations:    ['Atlantic Freight'],
        deliveryAddress: '99 Marine Drive, Table View, 7441',
        status:          'FAILED',
        invStatus:       'RETURN',
        condition:       'GOOD',
        failureNote:     'Recipient warehouse closed — rescheduled.',
    },
];
