import type { Address } from '@/types/addresses';

export const MOCK_ADDRESSES: Address[] = [
    {
        id: 'addr-1',
        fullName: 'John Doe',
        company: 'PickPackaging (Pty) Ltd',
        phone: '+27 21 555 0123',
        line1: '12 Buitenkant Street',
        line2: 'Unit 4A',
        city: 'Cape Town',
        province: 'Western Cape',
        postalCode: '8001',
        country: 'South Africa',
        type: 'both',
        isPrimary: true,
        usedInOrderCount: 5,
    },
    {
        id: 'addr-2',
        fullName: 'John Doe',
        company: 'JD Billing Services',
        phone: '+27 11 555 9876',
        line1: '88 Commissioner Street',
        city: 'Johannesburg',
        province: 'Gauteng',
        postalCode: '2000',
        country: 'South Africa',
        type: 'billing',
        isPrimary: false,
        usedInOrderCount: 2,
    },
    {
        id: 'addr-3',
        fullName: 'Jane Doe',
        line1: '45 Florida Road',
        city: 'Durban',
        province: 'KwaZulu-Natal',
        postalCode: '4001',
        country: 'South Africa',
        type: 'shipping',
        isPrimary: false,
        usedInOrderCount: 0,
    },
];
