import type { WishlistItem } from '@/types/wishlist';

export const MOCK_WISHLIST: WishlistItem[] = [
    // ── IN STOCK — price unchanged ────────────────────────────────────────────
    {
        id: 'wl-001',
        productId: 'prod-101',
        productName: 'Kraft Paper Mailer 250×350mm',
        sku: 'KPM-250350',
        vendorName: 'PackMaster SA',
        currentPrice: 45.00,
        savedPrice: 45.00,
        imageUrl: '',
        inStock: true,
        savedAt: '2025-05-01T08:20:00Z',
        quantity: 10,
    },
    {
        id: 'wl-002',
        productId: 'prod-102',
        productName: 'Corrugated Box A4 Single-Wall',
        sku: 'CBA4-SW',
        vendorName: 'BoxCo Industries',
        currentPrice: 18.50,
        savedPrice: 18.50,
        imageUrl: '',
        inStock: true,
        savedAt: '2025-05-02T10:45:00Z',
        quantity: 50,
    },
    // ── IN STOCK — price DROPPED (teal badge) ─────────────────────────────────
    {
        id: 'wl-003',
        productId: 'prod-103',
        productName: 'Stretch Wrap Film 500mm × 300m',
        sku: 'SWF-500300',
        vendorName: 'WrapRight',
        currentPrice: 189.00,
        savedPrice: 224.00,
        imageUrl: '',
        inStock: true,
        savedAt: '2025-04-28T14:10:00Z',
        quantity: 5,
    },
    {
        id: 'wl-004',
        productId: 'prod-104',
        productName: 'Bubble Wrap Roll 1000mm × 50m',
        sku: 'BWR-1000-50',
        vendorName: 'BubblePro',
        currentPrice: 310.00,
        savedPrice: 385.00,
        imageUrl: '',
        inStock: true,
        savedAt: '2025-04-25T09:30:00Z',
        quantity: 2,
    },
    // ── IN STOCK — price RISEN (amber badge) ──────────────────────────────────
    {
        id: 'wl-005',
        productId: 'prod-105',
        productName: 'Thermal Label Roll 100×150mm',
        sku: 'TLR-100150',
        vendorName: 'LabelTech',
        currentPrice: 2400.00,
        savedPrice: 2100.00,
        imageUrl: '',
        inStock: true,
        savedAt: '2025-04-20T11:00:00Z',
        quantity: 1,
    },
    // ── OUT OF STOCK ──────────────────────────────────────────────────────────
    {
        id: 'wl-006',
        productId: 'prod-106',
        productName: 'Cardboard Edge Protectors 50mm',
        sku: 'CEP-50',
        vendorName: 'EdgeGuard',
        currentPrice: 92.00,
        savedPrice: 92.00,
        imageUrl: '',
        inStock: false,
        savedAt: '2025-04-15T07:55:00Z',
        quantity: 20,
    },
    {
        id: 'wl-007',
        productId: 'prod-107',
        productName: 'Polypropylene Strapping Band 12mm',
        sku: 'PSB-12MM',
        vendorName: 'StrapSafe',
        currentPrice: 540.00,
        savedPrice: 540.00,
        imageUrl: '',
        inStock: false,
        savedAt: '2025-04-10T13:20:00Z',
        quantity: 3,
    },
    // ── IN STOCK — price unchanged ────────────────────────────────────────────
    {
        id: 'wl-008',
        productId: 'prod-108',
        productName: 'Pallet Wrap Dispenser Handle',
        sku: 'PWD-HANDLE',
        vendorName: 'WrapRight',
        currentPrice: 120.00,
        savedPrice: 120.00,
        imageUrl: '',
        inStock: true,
        savedAt: '2025-05-05T16:40:00Z',
        quantity: 1,
    },
];
