import { ManifestItem } from '@/types/rider/inventory';

export const MOCK_MANIFEST: ManifestItem[] = [
    {
        id: '1',
        sku: 'TLR-100150',
        productName: 'Thermal Label Roll 100×150mm',
        vendorName: 'LabelTech',
        thumbnailUrl: 'https://images.unsplash.com/photo-1605833559748-03820257326a?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 20,
        deliveredQty: 20,
        remainingQty: 0,
        maxWeightKg: 8.8,
        unitWeightKg: 0.44,
        condition: 'good',
        status: 'complete',
        destinations: ['Rapid Print Solutions'],
    },
    {
        id: '2',
        sku: 'KPM-250350',
        productName: 'Kraft Paper Mailer 250×350mm',
        vendorName: 'PackMaster SA',
        thumbnailUrl: 'https://images.unsplash.com/photo-1589939705384-5185138a047a?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 200,
        deliveredQty: 200,
        remainingQty: 0,
        maxWeightKg: 10,
        unitWeightKg: 0.05,
        condition: 'good',
        status: 'complete',
        destinations: ['Rapid Print Solutions'],
    },
    {
        id: '3',
        sku: 'CBA4-SW',
        productName: 'Corrugated Box A4 Single-Wall',
        vendorName: 'BoxCo Industries',
        thumbnailUrl: 'https://images.unsplash.com/photo-1529390079861-591de354faf5?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 150,
        deliveredQty: 150,
        remainingQty: 0,
        maxWeightKg: 42,
        unitWeightKg: 0.28,
        condition: 'good',
        status: 'complete',
        destinations: ['Greenleaf Packaging'],
    },
    {
        id: '4',
        sku: 'BWR-1000-50',
        productName: 'Bubble Wrap Roll 1000×50m',
        vendorName: 'PackMaster SA',
        thumbnailUrl: 'https://images.unsplash.com/photo-1595246140625-573b715d11dc?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 5,
        deliveredQty: 0,
        remainingQty: 5,
        maxWeightKg: 31.25,
        unitWeightKg: 6.25,
        condition: 'good',
        status: 'pending',
        destinations: ['Cape Carton Co.', 'Metro Logistics Hub'],
    },
    {
        id: '5',
        sku: 'CEP-50',
        productName: 'Cardboard Edge Protectors 50mm',
        vendorName: 'BoxCo Industries',
        thumbnailUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 60,
        deliveredQty: 15,
        remainingQty: 45,
        maxWeightKg: 7.2,
        unitWeightKg: 0.12,
        condition: 'partially_damaged',
        status: 'partial',
        destinations: ['Cape Carton Co.', 'Greenleaf Packaging'],
    },
    {
        id: '6',
        sku: 'SWF-500300',
        productName: 'Stretch Wrap Film 500mm×300m',
        vendorName: 'WrapRight',
        thumbnailUrl: 'https://images.unsplash.com/photo-1620912189865-1e8a33da4c59?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 8,
        deliveredQty: 0,
        remainingQty: 8,
        maxWeightKg: 28,
        unitWeightKg: 3.5,
        condition: 'good',
        status: 'pending',
        destinations: ['Metro Logistics Hub'],
    },
    {
        id: '7',
        sku: 'PWD-HANDLE',
        productName: 'Pallet Wrap Dispenser Handle',
        vendorName: 'WrapRight',
        thumbnailUrl: 'https://images.unsplash.com/photo-1589939705384-5185138a047a?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 4,
        deliveredQty: 0,
        remainingQty: 4,
        maxWeightKg: 1.8,
        unitWeightKg: 0.45,
        condition: 'good',
        status: 'pending',
        destinations: ['Metro Logistics Hub'],
    },
    {
        id: '8',
        sku: 'PSB-12MM',
        productName: 'Polypropylene Strapping Band 12mm',
        vendorName: 'StrapSafe',
        thumbnailUrl: 'https://images.unsplash.com/photo-1586769852836-bc069f19e1b6?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 10,
        deliveredQty: 0,
        remainingQty: 10,
        maxWeightKg: 26,
        unitWeightKg: 2.6,
        condition: 'good',
        status: 'return',
        destinations: ['Atlantic Freight'],
    },
    {
        id: '9',
        sku: 'TP-48MM-CL',
        productName: 'Packaging Tape 48mm Clear',
        vendorName: 'TapeWorld',
        thumbnailUrl: 'https://images.unsplash.com/photo-1589939705384-5185138a047a?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 72,
        deliveredQty: 0,
        remainingQty: 72,
        maxWeightKg: 14.4,
        unitWeightKg: 0.2,
        condition: 'damaged',
        status: 'pending',
        destinations: ['Cape Carton Co.'],
    },
    {
        id: '10',
        sku: 'CBA3-DW',
        productName: 'Corrugated Box A3 Double-Wall',
        vendorName: 'BoxCo Industries',
        thumbnailUrl: 'https://images.unsplash.com/photo-1512418490979-92798ced1380?q=80&w=200&h=200&auto=format&fit=crop',
        collectedQty: 40,
        deliveredQty: 0,
        remainingQty: 40,
        maxWeightKg: 16.8,
        unitWeightKg: 0.42,
        condition: 'good',
        status: 'pending',
        destinations: ['Greenleaf Packaging'],
    },
];

export const MOCK_VEHICLE = {
    registration: 'CA 456-789',
    type: '1-ton Bakkie',
    maxWeightKg: 300,
};
