import { DeliveryStop } from '@/types/rider/logistics';

export const MOCK_LOGISTICS_STOPS: DeliveryStop[] = [
    {
        id: 'stop-1',
        sequence: 1,
        status: 'completed',
        companyName: 'Cape Fresh Foods',
        address: '12 Marine Drive, Paarden Eiland, Cape Town',
        contactName: 'John Doe',
        contactPhone: '+27 21 555 0123',
        items: [{ sku: 'BOX-01', productName: 'Cardboard Box Large', qty: 50 }],
        estimatedArrival: '08:00',
        completedAt: '08:05',
    },
    {
        id: 'stop-2',
        sequence: 2,
        status: 'completed',
        companyName: 'Durban Industrial Supplies',
        address: '45 Umgeni Road, Durban Central',
        contactName: 'Sarah Smith',
        contactPhone: '+27 31 555 0456',
        items: [{ sku: 'TAPE-02', productName: 'Heavy Duty Packaging Tape', qty: 100 }],
        estimatedArrival: '08:45',
        completedAt: '08:52',
    },
    {
        id: 'stop-3',
        sequence: 3,
        status: 'failed',
        companyName: 'Jozi Tech Hub',
        address: '88 Rivonia Road, Sandton, Johannesburg',
        contactName: 'Michael Brown',
        contactPhone: '+27 11 555 0789',
        items: [{ sku: 'FILM-03', productName: 'Stretch Wrap Film', qty: 10 }],
        estimatedArrival: '09:30',
        failedReason: 'Recipient not available',
    },
    {
        id: 'stop-4',
        sequence: 4,
        status: 'completed',
        companyName: 'Garden Route Distro',
        address: '7 Knysna Way, George',
        contactName: 'Emily Davis',
        contactPhone: '+27 44 555 0101',
        items: [{ sku: 'PAL-04', productName: 'Wooden Pallet Standard', qty: 20 }],
        estimatedArrival: '10:15',
        completedAt: '10:20',
    },
    {
        id: 'stop-5',
        sequence: 5,
        status: 'completed',
        companyName: 'Pretoria Print Co.',
        address: '22 Church Street, Pretoria CBD',
        contactName: 'David Wilson',
        contactPhone: '+27 12 555 0202',
        items: [{ sku: 'ENV-05', productName: 'Padded Mailer Envelopes', qty: 500 }],
        estimatedArrival: '11:00',
        completedAt: '11:08',
    },
    {
        id: 'stop-6',
        sequence: 6,
        status: 'completed',
        companyName: 'Winelands Logistics',
        address: '33 Main Road, Stellenbosch',
        contactName: 'Lisa White',
        contactPhone: '+27 21 555 0303',
        items: [{ sku: 'LBL-06', productName: 'Thermal Shipping Labels', qty: 1000 }],
        estimatedArrival: '11:45',
        completedAt: '11:55',
    },
    {
        id: 'stop-7',
        sequence: 7,
        status: 'current',
        companyName: 'Acme Foods',
        address: '1 Sector 4 Industrial Park, Cape Town',
        contactName: 'Peter Parker',
        contactPhone: '+27 82 123 4567',
        items: [
            { sku: 'SKU-001', productName: 'Corrugated Box A4', qty: 12 },
            { sku: 'SKU-002', productName: 'Bubble Wrap 50m', qty: 2 },
            { sku: 'SKU-003', productName: 'Packaging Tape Clear', qty: 6 }
        ],
        estimatedArrival: '14:20',
        arrivedAt: '14:15',
    },
    // Generate 13 upcoming stops
    ...Array.from({ length: 13 }).map((_, i) => ({
        id: `stop-${i + 8}`,
        sequence: i + 8,
        status: 'upcoming' as const,
        companyName: [
            'Boland Beverages', 'Karoo Meats', 'Atlantic Seafood', 'Table Mountain Textiles',
            'Highveld Steel', 'Lowveld Fruit', 'Zululand Sugar', 'Limpopo Mining Supplies',
            'Free State Grain', 'Northern Cape Solar', 'Eastern Cape Auto', 'West Coast Fishing', 'Overberg Honey'
        ][i] || `Customer ${i + 8}`,
        address: `${Math.floor(Math.random() * 100)} Industrial Road, South Africa`,
        contactName: 'Contact Name',
        contactPhone: '+27 00 000 0000',
        items: [{ sku: 'SKU-ITEM', productName: 'Packaging Supply Item', qty: Math.floor(Math.random() * 50) + 1 }],
        estimatedArrival: `${15 + Math.floor(i / 2)}:${(i % 2) * 30 || '00'}`,
    }))
];
