import { DeliveryStop } from '@/types/rider/logistics';

export const MOCK_STOPS: DeliveryStop[] = [
    {
        id: 'stop-1',
        stopNumber: 1,
        status: 'completed',
        companyName: 'Rapid Print Solutions',
        address: '12 Loop Street, Cape Town CBD, 8001',
        contactName: 'Sarah Hendricks',
        contactPhone: '+27821234567',
        items: [
            { sku: 'TLR-100150', productName: 'Thermal Label Roll 100×150mm', qty: 20 },
            { sku: 'KPM-250350', productName: 'Kraft Paper Mailer 250×350mm', qty: 200 },
        ],
        etaTime: '08:45',
        deliveredAt: '08:47',
        podPhotoUrl: 'https://images.unsplash.com/photo-1568434710673-1d9e4d478b01?w=400',
    },
    {
        id: 'stop-2',
        stopNumber: 2,
        status: 'completed',
        companyName: 'Greenleaf Packaging',
        address: '7 Adderley Street, Cape Town CBD, 8001',
        contactName: 'Marcus Osei',
        contactPhone: '+27829876543',
        items: [
            { sku: 'CBA4-SW', productName: 'Corrugated Box A4 Single-Wall', qty: 150 },
            { sku: 'CBA3-DW', productName: 'Corrugated Box A3 Double-Wall', qty: 80 },
        ],
        etaTime: '09:30',
        deliveredAt: '09:38',
        podPhotoUrl: 'https://images.unsplash.com/photo-1568434710673-1d9e4d478b01?w=400',
    },
    {
        id: 'stop-3',
        stopNumber: 3,
        status: 'failed',
        companyName: 'Atlantic Freight',
        address: '99 Marine Drive, Table View, 7441',
        contactName: 'Yusuf Adams',
        contactPhone: '+27834567890',
        items: [
            { sku: 'PSB-12MM', productName: 'Polypropylene Strapping Band 12mm', qty: 12 },
        ],
        etaTime: '10:15',
        failureReason: 'Recipient warehouse closed — public holiday.',
    },
    {
        id: 'stop-4',
        stopNumber: 4,
        status: 'current',
        companyName: 'Cape Carton Co.',
        address: '34 Buitenkant Street, Gardens, Cape Town, 8001',
        contactName: 'Priya Naidoo',
        contactPhone: '+27845678901',
        items: [
            { sku: 'BWR-1000-50', productName: 'Bubble Wrap Roll 1000×50m', qty: 2 },
            { sku: 'CEP-50', productName: 'Cardboard Edge Protectors 50mm', qty: 60 },
            { sku: 'TP-48MM-CL', productName: 'Packaging Tape 48mm Clear', qty: 72 },
        ],
        etaTime: '14:20',
        arrivalMins: 12,
    },
    {
        id: 'stop-5',
        stopNumber: 5,
        status: 'upcoming',
        companyName: 'Metro Logistics Hub',
        address: '1 Voortrekker Road, Bellville, 7530',
        contactName: 'Deon Swart',
        contactPhone: '+27856789012',
        items: [
            { sku: 'SWF-500300', productName: 'Stretch Wrap Film 500mm×300m', qty: 8 },
            { sku: 'PWD-HANDLE', productName: 'Pallet Wrap Dispenser Handle', qty: 4 },
        ],
        etaTime: '15:10',
    },
    {
        id: 'stop-6',
        stopNumber: 6,
        status: 'upcoming',
        companyName: 'Harbour Industrial Supplies',
        address: '45 Koeberg Road, Milnerton, 7435',
        contactName: 'Ané van Wyk',
        contactPhone: '+27867890123',
        items: [
            { sku: 'CEP-50', productName: 'Cardboard Edge Protectors 50mm', qty: 100 },
        ],
        etaTime: '15:55',
    },
    {
        id: 'stop-7',
        stopNumber: 7,
        status: 'upcoming',
        companyName: 'SurePack Distributors',
        address: '88 Paarden Eiland Road, Cape Town, 7405',
        contactName: 'Tshepo Mokoena',
        contactPhone: '+27878901234',
        items: [
            { sku: 'CBA4-SW', productName: 'Corrugated Box A4 Single-Wall', qty: 50 },
            { sku: 'KPM-250350', productName: 'Kraft Paper Mailer 250×350mm', qty: 100 },
        ],
        etaTime: '16:40',
    },
];
